<!DOCTYPE html>
<html>
    <head>
        <script src="http://code.jquery.com/jquery.min.js"></script>
        <link href="http://getbootstrap.com/dist/css/bootstrap.css"
        	rel="stylesheet" type="text/css" />
		<link href="http://cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css" rel="stylesheet" type="text/css" />
		<link href="http://cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.print.css " rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.min.js" />
        <script src="http://getbootstrap.com/dist/js/bootstrap.js"></script>
        <meta charset=utf-8 />
        <style>
            @font-face {
                font-family: ProximaNova;
            	src: url("/hackru/public/pn.otf") format("opentype");	
            }
            
            html, body, .container { 
            	font-family: ProximaNova;
            	padding-top: 5px;
            	height: 800px; 
                width: 1200px; 
            	min-height: 800px;
            	min-width: 1200px;
            	margin: 0 auto;
            	
            	font-size: 1em; 
            	background: whitesmoke;
            }
            
            .row.top { 
                height: 50px; 
            	line-height: 50px;
            	font-size: 40px;
            }
            
            .row.middle { 
                height: 590px; 
            }
            
            .row.bottom {
            	height: 160px;
            }
            
            .fill-height {
            	height: 100%;
            }
            
            .vert-center-10 {
            	position: absolute;
            	height: 80%;
            	top: 10%;
            	display: table-cell;
            	vertical-align: middle;            	
            }
            .daily-wrapper {
            	width: calc(100% - 30px);
            }
            .white { 
            	background: white;
            }
            .funds span {
            	margin-right: 15px;            	
            }
            
            .funds .available {
            	color: green;
            }
            .funds .held {
            	color: red;
            }
            
            .well {
            	background: url('/hackru/public/img/sos.png');
            }
            
            li
			{
				list-style:none;
			}
			
			li.to-do
			{
				padding-bottom: 30px;
			}
			
			.to-do ul
			{
				padding:0 0 0 10px;
				float:right;
				width:340px;
			}
			
			.to-do.img
			{
				width:90px;
			}
			
			li.stake
			{
				padding-top:25px;
			}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row top">
                <div class="col-sm-12">
                    <div class="pull-left">
                        <span class='large'>Exercise Enforcer</span>
                    </div>
                    <div class="pull-right">
                        <?php echo $this->userFunds(); ?>
                        <a href='<?php echo $this->url(array('controller'=>'user', 'action'=>'index'), null, true) ?>'>Calendar</a>                    
                        <a href='<?php echo $this->url(array('controller'=>'user', 'action'=>'settings'), null, true) ?>'>Settings</a>                    
                    </div>
                </div>
            </div>        
            <?php echo $this->layout()->content; ?>
        </div>
        
        <script type="text/javascript">
		$(document).ready(function() 
		{
			// page is now ready, initialize the calendar...
			$('#calendar').fullCalendar(
			{
				// put your options and callbacks here
			});
		});
		</script>
    </body>
</html>