<div class="row middle">
    <div class="col-sm-7 fill-height">
        <div class="col-sm-11 vert-center-10">
            <div id='calendar'></div>
        </div>
    </div> 
    <div class="col-sm-5 fill-height">
        <div class="vert-center-10 daily-wrapper">
            <div class='secondary hidden'>
                <form class='form' id='add-task-form' method='post'
                    action='<?php echo $this->url(array('controller'=>'tasks', 'action'=>'add'), null, true)?>'>
                    <div class="form-group">
                        <input placeholder="Describe Goal" class='form-control' name='title' value='' required type='text' />
                    </div>
                    <div class='form-group'>
                        <label>FourSquare Category</label>
                        <select name='category' required class='form-control'>
                            <?php foreach($this->categories as $id => $name) { ?>
                            <option value=<?php echo $id ?>><?php echo $name ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class='form-group'>
                        <label>Wager ($)</label>
                        <input value='1' name='wager' class='form-control' type='number' required min='.5' step='.5'/>
                    </div>
                    <div class='form-group'>
                        <input placeholder="Start Date" class='date form-control' name='start' value='' required type='text' />
                    </div>
                    <div class='form-group'>
                        <input placeholder="End Date" class='date form-control' name='end' value='' required type='text' />
                    </div>
                    <div class='form-group'>
                        <button class='btn btn-primary btn-lg btn-block' 
                            type='submit'><h3>Create</h3></button>
                    </div>
                    <div class='form-group'>
                        <button id='cancel' class='btn btn-lg btn-block btn-default'>
                            Cancel
                        </button>
                    </div>
                    <input type='hidden' name='redirect' value='<?php echo $this->url(array('controller'=>'user', 'action'=>'index'), null, true) ?>'/>
                </form>
            </div>
            <div class='main'>
                <ul>
                    <li class='margin-bottom-30'>
                        <button id="create-goal" class='btn btn-primary btn-lg btn-block'>
                            <h3>Create Goal</h3>
                        </button>
                    </li>
                </ul>
                <ul style="height: 392px; overflow: auto;">
                    <?php foreach($this->todayTasks as $task) { ?>
                    <?php $class = $task['completed'] ? "completed" : "incomplete" ?>
                    <li class="clearfix to-do <?php echo $class; ?>">
                        <img class='pull-left' src="img/4sq/<?php echo $task['category'] ?>.jpg" />
                        <ul>
                            <li>Goal: <?php echo $task['title'] ?></li>
                            <li>Due: <?php echo date('m-d-Y',$task['end']) ?></li>
                            <li class="stake">Wager: $<?php echo number_format($task['wager'], 2) ?></li>
                        </ul>
                    </li>
                    <?php } ?>
    			</ul>
            </div>
        </div>
    </div>
</div>
<div class="row bottom">
    <div class="col-sm-4">
        <div class="col-sm-12">
            1
        </div>
    </div>
    <div class="col-sm-4">
        2
    </div>
    <div class="col-sm-4">
        3
    </div>
</div>

<script type="text/javascript">
$("#create-goal").click(function() {
	$(".main").toggleClass("hidden");
	$(".secondary").toggleClass("hidden");
});

$("#cancel").click(function(e) {
	$(".main").toggleClass("hidden");
	$(".secondary").toggleClass("hidden");
	
    e.preventDefault();
    return false;
});

$(".date").datepicker({
	dateFormat: 'yy-mm-dd'
});

</script>