<div class="row middle">
    <div class="col-sm-7 fill-height">
        <div class="col-sm-11 vert-center-10">
            <div id='calendar'></div>
        </div>
    </div> 
    <div class="col-sm-5 fill-height">
        <div class="vert-center-10 daily-wrapper">
            <div class='secondary hidden'>
                <form class='form' id='add-task-form' method='post'
                    action='<?php echo $this->url(array('controller'=>'tasks', 'action'=>'add'), null, true)?>'>
                    <script
                        src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
                        data-key="pk_test_czwzkTp2tactuLOEOqbMTRzG"
                        data-amount="2000"
                        data-name="ActiveVault"
                        data-description="1 wager ($10.00)"
                        data-image="/128x128.png">
                    </script>
                    <div class="form-group">
                        <input placeholder="Describe Goal" class='form-control' name='title' value='' required type='text' />
                    </div>
                    <div class='form-group'>
                        <label>FourSquare Category</label>
                        <select name='category' required class='form-control'>
                            <?php foreach($this->categories as $id => $name) { ?>
                            <option value=<?php echo $id ?>><?php echo $name ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class='form-group'>
                        <label>Wager ($)</label>
                        <input value='1' name='wager' class='form-control' type='number' required min='1' step='1'/>
                    </div>
                    <div class='form-group'>
                        <input placeholder="Start Date" class='date form-control' name='start' value='' required type='text' />
                    </div>
                    <div class='form-group'>
                        <input placeholder="End Date" class='date form-control' name='end' value='' required type='text' />
                    </div>
                    <div class='form-group'>
                        <button class='btn btn-primary btn-lg btn-block' 
                            type='submit'><h3>Create</h3></button>
                    </div>
                    <div class='form-group'>
                        <button id='cancel' class='btn btn-lg btn-block btn-default'>
                            Cancel
                        </button>
                    </div>
                    <input type='hidden' name='redirect' value='<?php echo $this->url(array('controller'=>'user', 'action'=>'index'), null, true) ?>'/>
                </form>
            </div>
            <div class='main'>
                <ul>
                    <li class='margin-bottom-30'>
                        <div class='btn-group btn-group-lg btn-group-block'>
                            <button id="create-goal" class='btn btn-primary'>
                                <h3>Create Goal</h3>
                            </button>
                            <button id="check-4sq" class='btn btn-primary'>
                                <h3>4Square Sync</h3>
                            </button>
                        </div>
                    </li>
                </ul>
                <h2>Today's Unfinished Goals</h2>
                <ul style="height: 392px; overflow: auto;">
                    <?php foreach($this->todayTasks as $task) { ?>
                    <?php $class = $task['completed'] ? "completed" : "incomplete" ?>
                    <li class="clearfix to-do <?php echo $class; ?>">
                        <img class='pull-left' src="img/4sq/<?php echo $task['category'] ?>.jpg" />
                        <ul>
                            <li>Goal: <?php echo $task['title'] ?></li>
                            <li>@ <?php echo $task['category-name'] ?></li>
                            <li>Due: <?php echo date('m-d-Y',$task['end']) ?></li>
                            <li class="stake">Wager: $<?php echo number_format($task['wager'], 2) ?></li>
                        </ul>
                    </li>
                    <?php } ?>
    			</ul>
            </div>
        </div>
    </div>
</div>
<div class="row bottom">
    <div class="col-sm-4">
        <div class="col-sm-12">
            1
        </div>
    </div>
    <div class="col-sm-4">
        2
    </div>
    <div class="col-sm-4">
        3
    </div>
</div>

<script type="text/javascript">
$("#create-goal").click(function() {
	$(".main").toggleClass("hidden");
	$(".secondary").toggleClass("hidden");
});

$("#check-4sq").click(function() {
	window.location.href = '<?php echo $this->url(array('action'=>'callback'), null, true)?>';
});
$("#cancel").click(function(e) {
	$(".main").toggleClass("hidden");
	$(".secondary").toggleClass("hidden");
	
    e.preventDefault();
    return false;
});

$(".date").datepicker({
	dateFormat: 'yy-mm-dd'
});
$('#calendar').fullCalendar({
	height: 500,
    events: [
        <?php foreach($this->allTasks as $task) { ?>
        <?php 
            $color = '#d9edf7';
            $textColor = '#3a87ad';
            $border = '#bce8f1';
            if($task['completed'])
            {
                if($task['success'])
                {
                    $color = '#dff0d8';
                    $textColor = '#468847';
                    $border = '#d6e9c6';
                }
                else
                {
                    $color = '#f2dede';
                    $textColor = '#b94a48';
                    $border = '#eed3d7';
                }
            }
        ?>
        {
            title: '<?php echo $task['title'] ?>',
            start : '<?php echo date("Y-m-d", $task['start']) ?>',
            end : '<?php echo date("Y-m-d", $task['end']) ?>',
            <?php if ($color) { ?>
            color: '<?php echo $color ?>',
            textColor: '<?php echo $textColor?>',
            borderColor: '<?php echo $border?>',
            <?php } ?>
        },
        <?php } ?>
    ],
});
$('#calendar').fullCalendar('option', 'height', .8*600);
</script>
