<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<div class='row'>
    <div class='col-sm-6 col-sm-offset-3'>
        <h1>Add Funds</h1>
        <div id="add-funds-wrapper" class='well'>
            <p>
            Use this to fund your account and continue to use our services. We only accept
            payments greater than 10$, and any failed exercise attempts will be donated 100%
            to charity.
            </p>
            <form id="add-funds" class="form" method="post" 
                action="<?php echo $this->url(array('controller'=>'funds', 'action'=>'add'), null, true) ?>">
                <div class='form-group'>
                    <label>Amount($)</label>
                    <input class='form-control'  required id="add-funds-amount" type="number" name='amount' min="10" />
                </div>
                <div class='form-group'>
                    <label>Card Number</label>
                    <input class='form-control' required type="text" name='card' />
                </div>
                <div class='form-group'>
                    <label>MM</label>
                    <input class='form-control'  required type="text" name='month' />
                </div>
                <div class='form-group'>
                    <label>YYYY</label>
                    <input class='form-control'  required type="text" name='year' />
                </div>
                <div class='form-group'>
                    <input class='btn btn-primary' type='submit' value='Add Funds!' />
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
$("#add-funds").submit(function(e) {

    var self = $(this);

    var card = self.find("input[name='card']").val();
    var mm = self.find("input[name='month']").val();
    var yyyy = self.find("input[name='year']").val();

    Stripe.card.createToken({
        number: card,
        exp_month: mm,
        exp_year: yyyy
    }, function(status, response) {
        if(response.error)
        {
            console.log(response.error);
        }
        else
        {
            var token = response['id'];
            self.find("input[type='submit']")
		      .attr('disabled', 'disabled')
		      .attr('value', 'Wait for it...');
            $.post(self.attr('action'), self.serialize() + "&token=" + token)
             .success(function(data) {
        		data = JSON.parse(data);
        		self.parent().find(".alert").remove();
        	    if(data['status'] == 200)
        	    {
        		    self.find("input[type='submit']")
        		      .attr('disabled', 'disabled')
        		      .attr('value', 'Success!');
        		    $(".funds .available").text(data.free);
        		    var alert = $("<p class='alert alert-success'>Funds Added Successfully.</p>");
        		    $("#add-funds-wrapper").prepend(alert);
        	    }
        	    else
        	    {  
        	    	var alert = $("<p class='alert alert-danger'>" + data.error + "</p>");
        		    $("#add-funds-wrapper").prepend(alert);
        		    self.find("input[type='submit']")
        		      .attr('disabled', null)
        		      .attr('value', 'Add Funds!');
        	    }
        	});
        }
    });
	
    e.preventDefault();
    return false;
});

Stripe.setPublishableKey("pk_test_czwzkTp2tactuLOEOqbMTRzG");
</script>